### ISSUE TITLE
If app is in background mode then entry and exit not working

### ISSUE THREAD

**Issue by sarishti** [michaelmika/react-native-simple-native-geofencing#3]
If app is in background mode/ kill state then entry and exit not working in case of android

**Comment by michaelmika** [comment]
Do you mean the "Monitoring Geofence" or a "normal" Geofence? This library uses the native Geofencing abilities of the OS (See: [Android](https://developer.android.com/training/location/geofencing) or [iOS](https://developer.apple.com/documentation/corelocation/monitoring_the_user_s_proximity_to_geographic_regions). It's limited to the native's abilities (e.g. number of geofences, OS version, etc.). It is not the most accurate geofencing, but batterie saving and efficient, that's why it can sometimes take a bit to get the notification. Which OS are you using? 

In case you mean the "Monitoring Geofence" check the Topic in the Docs (at the end) for it's implementation depending the OS.

**Comment by sarishti** [comment]
I am using normal geofence and I am using OS version 9 on s8 device. In case of ios It is working fine during background mode and push me notification but in android it is not working.

**Comment by michaelmika** [comment]
Have you enabled your device to let Apps use high (fine) accuracy location? [See here](https://support.google.com/android/answer/3467281?hl=en).
This module does not ask if the permission is granted (because I had trouble in another Project with it). You might want to ask the user at the beginning of your App. It is pretty simple in React:

```
async function requestLocationPermission() {
  try {
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
      {
        title: 'Location Permission for geofencing',
        message:
          'We need that permission for the geofencing feature',
        buttonNeutral: 'Ask Me Later',
        buttonNegative: 'Cancel',
        buttonPositive: 'OK',
      },
    );
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
      console.log('You can use the Location now');
    } else {
      console.log('Location permission denied');
    }
  } catch (err) {
    console.warn(err);
  }
}
```
[see react docs](https://facebook.github.io/react-native/docs/permissionsandroid)

**Comment by ghost** [comment]
I think after Oreo (Android 8) they don't let you do location stuff Inna back ground service and you have to start a foreground service with a notification. I might be wrong but it looks similar to this issue in another module which has a fork to fix it.

https://github.com/eddieowens/react-native-boundary/issues/45
