### ISSUE TITLE
Background not working Android

### ISSUE THREAD

**Issue by titoxix** [michaelmika/react-native-simple-native-geofencing#4]
Hi,
In android app in background not working.

**Comment by michaelmika** [comment]
Do you mean the "Monitoring Geofence" or a "normal" Geofence? This library uses the native Geofencing abilities of the OS (See: [Android](https://developer.android.com/training/location/geofencing)). It's limited to the native's abilities (e.g. number of geofences, OS version, etc.). It is not the most accurate geofencing, but batterie saving and efficient, that's why it can sometimes take a bit to get the notification. 

In case you mean the "Monitoring Geofence" check the Topic in the Docs (at the end) for it's implementation (with HeadlessJS).

**Comment by calypsow777** [comment]
Hello,
I am using the "normal" geofences and I do receive the notifications when the app is in foreground (on Android).
However, when the app is in background I don't receive any notification and I can see this line in my logs:
`W ActivityManager: Background start not allowed: service Intent { cmp=com.aaaaa/com.simplegeofencing.reactnative.GeofenceTransitionsIntentService (has extras) } to com.aaaa/com.simplegeofencing.reactnative.GeofenceTransitionsIntentService from pid=-1 uid=10433 pkg=com.aaaa startFg?=false`
